/**
 * categoriesConfig.js — Classement automatique des témoignages
 * ─────────────────────────────────────────────────────────────────
 * • Les mots-clés sont lus depuis config.json (clé "categoriesKeywords")
 *   via getConfig(), donc modifiables SANS redéploiement.
 * • Si config.json ne contient pas de mots-clés, on retombe sur la
 *   liste par défaut DEFAULT_KEYWORDS ci-dessous.
 * • Normalisation : minuscules + suppression des accents.
 * • Variantes anglaises incluses dans les listes.
 */

// ── Liste par défaut (43 catégories fusionnées) ───────────────────
// Utilisée uniquement si config.json ne définit pas categoriesKeywords.
const DEFAULT_KEYWORDS = {
  "Guérison": ["guérison","guérir","guéri","guéris","guérie","guéries","healed","healing","heal","rétablissement","rétablir","rétabli","rétablie","soigner","soigné","soignée","santé","sain","saine","remède","traitement","thérapie","guérisseur","médecin","docteur","chirurgien","infirmier","infirmière","hôpital","clinique","cancer","tumeur","diabète","infection","blessure","cicatrice","handicap","paralysie","maladie","malade","douleur","douleurs","souffrance","miracle","miraculeux","dieu m'a guéri","je suis guéri"],
  "Prière": ["prière","prier","prié","priait","prières","prions","priant","intercession","intercéder","supplication","supplier","demander à dieu","demander au seigneur","oraison","orant","orants","rosaire","chapelet","adoration","adorer","invocation","prayer","pray","prayed","praying"],
  "Église": ["église","paroisse","paroissien","paroissienne","communauté chrétienne","communauté","assemblée","culte","service religieux","service divin","liturgie","eucharistie","communion","messe","prêtre","curé","évêque","diacre","pasteur","ministre","diaconie","diaconesse","sacrement","baptême","confirmation","lundi de pâques","dimanche des rameaux","temple","sanctuaire","congrégation","church","parish","pastor","priest","liturgy"],
  "Famille": ["famille","familial","familiale","enfant","enfants","fils","fille","bébé","nourrisson","parent","parents","père","mère","maman","papa","frère","soeur","frères","soeurs","mari","époux","épouse","femme","grand-mère","grand-père","grand-mères","grand-pères","mariage","marié","mariée","mariés","marier","se marier","divorce","divorcé","divorcée","concubinage","conjoint","conjointe","relation familiale","lien familial","enfance","adolescent","adolescence"],
  "Santé": ["santé","sain","saine","santé physique","maladie","malade","mal-être","virus","viral","grippe","covid","covid-19","coronavirus","infection","infecté","fièvre","fièvreux","fatigue","fatigué","fatiguée","douleur","douleurs","douloureux","douloureuse","symptôme","symptômes","diagnostic","diagnostique","diagnostiqué","traitement","traiter","soins","soigner","soigné","médecin","docteur","infirmier","infirmière","hôpital","clinique","ambulance","urgence","médicament","médicaments","pilule","comprimé","injection","santé mentale","dépression","anxiété","angoisse","trouble","allergie","allergique","disability","disease","illness","medicine","hospital","pathologie","pathologique","syndrome","syndromes","affection","affections","épidémie","épidémique","morbidité","morbide"],
  "Foi": ["foi","croire","croyance","croyant","croyante","croyants","croyantes","confiance en dieu","confiance au seigneur","fidèle","fidèles","fidélité","incroyance","incroyant","athée","athéisme","conversion","converti","convertie","convertis","convertir","retour à dieu","retour à la foi","testifier","témoignage","témoignage de foi","grace","grâce","grâces","bénédiction","bénédictions","béni","bénie","bénits","bénies","miracle","miraculeux","miraculeusement","divin","divinité","providence","confessional","confession","confesser","croyance religieuse","conviction religieuse","faith","believe","believer","blessing"],
  "Paix et Repos": ["paix","paisible","paisiblement","repos","reposer","se reposer","reposé","reposée","sérénité","serein","sereine","tranquillité","tranquille","tranquilles","calme","calmer","calmé","calmée","soulagement","soulager","soulagé","soulagée","détente","se détendre","bien-être","silence","silencieux","silencieuse","refuge","asile","sanctuaire","paix de dieu","paix du seigneur","peace","rest","calm","serenity","tranquil"],
  "Vie de couple": ["couple","amour","amoureux","amoureuse","aimer","aimé","aimée","mariage","marié","mariée","mariés","marier","se marier","époux","épouse","mari","femme","concubinage","concubin","concubine","vie commune","amant","maîtresse","séduction","séduire","passion","passionné","passionnée","complicité","complice","relation amoureuse","relation intime","divorce","divorcer","divorcé","divorcée","infidélité","infidèle","jalousie","jaloux","jalouse","réconciliation","se réconcilier","réconcilié","réconciliée","romance","love","marriage","spouse"],
  "Education des enfants": ["enfant","enfants","fils","fille","éducation","éduquer","éducatif","éducative","parents","parent","père","mère","maman","papa","scolarité","école","scolaire","scolarisé","scolarisée","enseignement","enseigner","enseigné","enseignée","apprentissage","apprendre","discipline","discipliner","disciplinaire","obéissance","obéir","obéissant","obéissante","insolence","insolent","insolente","rébellion","rebelle","adolescent","adolescence","ado","jeunesse","jeune","autorité parentale","correction","corriger","punition","punir","récompense","récompenser","conseils parentaux","education","children","parenting","obedience"],
  "Amour": ["amour","aimer","aimé","aimée","aimés","aimées","amoureux","amoureuse","affection","affectueux","affectueuse","tendresse","tendre","compassion","compassionnel","compatir","charité","charitable","bienveillance","bienveillant","bienveillante","bonté","bon","bonne","dévouement","dévoué","dévouée","sacrifice","sacrifier","sacrifié","sacrifiée","don de soi","se donner","fidélité","fidèle","loyauté","loyal","loyale","altruisme","altruiste","générosité","généreux","généreuse","amour divin","amour de dieu","dieu nous aime","love","charity","kindness","devotion","affection"],
  "Avenir": ["avenir","futur","futuriste","espoir","espérer","espérant","plan","planification","planifier","planifié","projet","projets","projet de vie","destination","destiné","destinée","perspective","carrière","professionnel","ambition","ambitieux","ambitieuse","rêve","rêver","rêvé","rêvée","rêves","vision","visionnaire","confiance en l'avenir","incertitude","incertain","incertaine","appréhension","appréhender","anxiété","angoisse","promesse divine","promesses de dieu","future","hope","aspiration","dream","destiny"],
  "Appel de Dieu": ["appel","appeler","appelé","appelée","appelés","appelées","vocation","vocable","mission","missionnaire","destinée divine","destin divin","élection","élu","élue","élus","élues","choix divin","choisir par dieu","consécration","consacrer","consacré","consacrée","ordination","ordonné","ordonnée","sacerdoce","prêtrise","congrégation religieuse","monachisme","moine","moniale","religieux","religieuse","dieu m'a appelé","suivre l'appel de dieu","calling","vocation","mission","priesthood"],
  "Bénédiction Bibliques": ["bénédiction","bénédictions","béni","bénie","bénits","bénies","bénir","bénissant","grâce","grâces","gracieux","gracieuse","providence","providentiel","providentielle","faveur","favorisé","favorisée","multiplication","multiplier","multiplié","multipliée","abondance","abondant","abondante","richesse","riche","riches","prospérité","prospère","protection","protéger","protégé","protégée","garde divine","gardien","bénédictions du seigneur","béni soit le seigneur","blessing","blessed","abundance","favor","prosperity"],
  "Compassion": ["compassion","compatir","compatissant","compatissante","empathie","empathique","sympathie","sympathique","pitié","pitoyable","miséricorde","miséricordieux","miséricordieuse","attendrissement","attendrir","attendri","attendrie","sensibilité","sensible","bienveillance","bienveillant","bienveillante","douceur","doux","douce","gentillesse","gentil","gentille","mansuétude","humanité","humanitaire","fraternité","fraternel","fraternelle","solidarité","solidaire","entraide","entraider","empathy","mercy","gentleness"],
  "Evangelisation": ["évangélisation","évangéliser","évangélisé","évangélisée","évangile","évangélique","évangéliques","mission","missionnaire","missionner","prédication","prêcher","prêché","prêchée","conversion","converti","convertie","convertir","témoin","témoignage","témoigner","proclamation","proclamer","proclamé","proclamée","propagation de la foi","diffusion de la foi","apostolat","apostolique","disciple","annonce de l'évangile","annonce de bonne nouvelle","partager la bonne parole","propager la foi","evangelism","evangelist","gospel","witness"],
  "Encouragement": ["encouragement","encouragements","encourager","encouragé","encouragée","soutien","soutenir","soutenu","soutenue","réconfort","réconforter","réconforté","réconfortée","appui","appuyer","aide","aider","aidé","aidée","assistance","assistant","assistante","motivation","motiver","motivé","motivée","inspiration","inspirer","inspiré","inspirée","exemple","exemplaire","parole encourageante","consolation","consoler","consolé","consolée","réaffirmation","certitude","force","fortifier","confiance","confiant","confiante","dieu est avec toi","support","motivation","inspiration","comfort"],
  "Engagement": ["engagement","s'engager","engagé","engagée","commitment","promesse","promesses","promettre","promis","promise","vœu","vœux","voeu","alliance","allié","alliée","fidélité","fidèle","fidèles","dévouement","dévoué","dévouée","consécration","consacrer","consacré","consacrée","détermination","déterminé","déterminée","résolution","résolu","résolue","fermeté","ferme","constance","constant","constante","persévérance","persévérant","persévérante","ténacité","tenace","loyauté","loyal","loyale","je m'engage","j'ai décidé","dedication","loyalty","determination"],
  "Fatigue": ["fatigue","fatigué","fatiguée","fatigués","fatiguées","épuisement","épuisé","épuisée","épuisés","épuisées","lassitude","las","lasse","burn-out","syndrome d'épuisement","surmenage","surmené","surmenée","fatigue physique","fatigue mentale","fatigue spirituelle","torpeur","torpide","somnolence","somnolent","somnolente","apathie","apathique","découragement","découragé","découragée","affaiblissement","affaibli","affaiblie","usure","usé","usée","exhaustion","tiredness","burnout","weariness"],
  "Générosité financière": ["générosité","généreux","généreuse","généreusement","don","donner","donné","donnée","dons","aumône","aumonier","offrande","offrir","offert","offerte","partage","partager","partagé","partagée","charité","charitable","dîme","dîmer","dîmé","dîmée","contribution","contribuer","contribué","contribuée","aide financière","soutien financier","entraide","entraider","altruisme","altruiste","sacrifice","sacrifier","sacrifié","sacrifiée","libéralité","libéral","libérale","richesse partagée","argent partagé","dieu récompense","generosity","donation","giving","sharing","tithe"],
  "Grâce de Dieu": ["grâce","grâces","gracieux","gracieuse","grâce divine","grâce du seigneur","bénédiction","bénédictions","béni","bénie","faveur divine","faveur de dieu","mercy","merciful","miséricorde","miséricordieux","miséricordieuse","providence","providentiel","providentielle","bienveillance divine","pardon","pardonner","pardonné","pardonnée","rédemption","rédempteur","rédemptrice","racheté","rachetée","justification","justifier","justifié","justifiée","sainteté","saint","sainte","illumination","illuminer","illuminé","illuminée","grâce sanctifiante","par la grâce de dieu","redemption","forgiveness","divine mercy"],
  "Idolâtrie": ["idolâtrie","idolâtre","idolâtres","idole","idoles","culte des idoles","culte idolâtrique","faux dieu","faux dieux","divinité païenne","paganisme","païen","païenne","polythéisme","polythéiste","matérialisme","matérialiste","attachement mondain","attachement terrestre","convoitise","convoiter","convoité","convoitée","richesse","argent","possession","possession matérielle","vanité","vanités","vaniteux","vaniteuse","orgueil","orgueilleux","orgueilleuse","divinisation","culte","cultuel","cultuelle","servir les idoles","adorer les faux dieux","idolatry","idol","false god","paganism"],
  "Jeûne & Prière": ["jeûne","jeûner","jeûné","jeûnée","carême","carêmé","carêmée","abstinence","s'abstenir","abstenu","abstenue","mortification","mortifier","mortifié","mortifiée","prière","prier","prié","priait","prières","prions","priant","intercession","intercéder","supplication","supplier","adoration","adorer","prière et jeûne","jeûne et prière","sacrifice personnel","renoncement","discipline spirituelle","ascèse","ascétisme","pénitence","pénitent","pénitente","expiation","expier","expié","expiée","contrition","contrit","contrite","fasting","abstinence","penance"],
  "Jugement et Pardon": ["jugement","juger","jugé","jugée","pardon","pardonner","pardonné","pardonnée","pardons","se pardonner","réconciliation","réconcilier","réconcilié","réconciliée","miséricorde","miséricordieux","miséricordieuse","clémence","clément","clémente","indulgence","indulgent","indulgente","grâce","gracieux","gracieuse","rédemption","rédempteur","rédemptrice","absolution","absoudre","absout","absoute","condamnation","condamner","condamné","condamnée","repentir","repentant","repentante","se repentir","regret","regretter","regretté","regrettée","colère divine","colère de dieu","jugement divin","dieu pardonne","forgiveness","pardon","clemency","judgment"],
  "Les vertus": ["vertu","vertus","vertueux","vertueuse","moralité","moral","morale","moralement","justice","juste","justement","prudence","prudent","prudente","tempérance","tempérant","tempérante","force","fort","forte","courage","courageux","courageuse","sagesse","sage","humilité","humble","humblement","chasteté","chaste","obéissance","obéir","obéissant","obéissante","modération","modéré","modérée","probité","probe","intégrité","intègre","virtue","wisdom","courage","prudence"],
  "Occasion Particulière": ["occasion","occasionnel","occasionnelle","fête","fêtes","festif","festive","noël","noels","christmas","pâques","pâque","easter","ascension","ascensionnel","ascensionnelle","pentecôte","whitsun","épiphanie","toussaint","tous les saints","fête religieuse","fête chrétienne","célébration","célébrer","célébré","célébrée","anniversaire","anniversaires","jubilé","jubilaire","commémoration","commémorer","commémoré","commémorée","solennité","solennel","solennelle","fêtes de noël","ascension du seigneur","holiday","celebration","feast","anniversary"],
  "Obéissance": ["obéissance","obéir","obéissant","obéissante","obéissances","obéis","obéissons","soumission","se soumettre","soumis","soumise","inobéissance","désobéissance","désobéir","désobéissant","désobéissante","commandement","commandements","commander","ordonnance","ordonnances","loi","lois","légal","légale","règle","règles","réglementaire","discipline","discipliner","autorité","autoritaire","hiérarchie","hiérarchique","subordination","subordonné","subordonnée","ordre","ordonner","ordonné","ordonnée","obéir à dieu","dieu ordonne","obedience","submission","obey","commandment"],
  "Péché": ["péché","péchés","pécheur","pécheresse","pécheurs","pécheresses","transgression","transgresser","transgressé","transgressée","faute","fautes","culpabilité","culpable","remords","honte","honteux","honteuse","condamnation","condamner","culpabilité spirituelle","culpabilité morale","immoralité","immoral","immorale","impureté","impur","impure","luxure","luxurieux","luxurieuse","avarice","avare","orgueil","orgueilleux","orgueilleuse","envie","envieux","envieuse","colère","gourmandise","gourmand","gourmande","paresse","paresseux","paresseuse","libre du péché","sans péché","se repentir du péché","sin","sinner","transgression","guilt","shame"],
  "Persévérance": ["persévérance","persévérant","persévérante","persévérer","constance","constant","constante","ténacité","tenace","détermination","déterminé","déterminée","résolution","résolu","résolue","fermeté","ferme","endurance","endurant","endurante","endurer","patience","patient","patiente","obstination","obstiné","obstinée","insistance","insistant","insistante","continuité","continu","continue","courage","courageux","courageuse","volonté","volontaire","je ne lâcherai pas","dieu me donne la force","perseverance","persistence","endurance","tenacity"],
  "Personnage de la Bible": ["personnage","personnages","biblique","bibliques","jesus","christ","jésus-christ","messie","marie","mère de jesus","joseph","joseph de nazareth","moïse","moise","david","roi david","abraham","noé","arche de noé","samson","dalila","goliath","marie-madeleine","madeleine","pierre","pierre l'apôtre","céphas","paul","saul","judas","judas iscariote","jean","jean l'évangéliste","jean le baptiseur","matthieu","matthieu l'apôtre","luc","luc l'évangéliste","marc","marc l'évangéliste","apocalypse","jean de patmos","personnage biblique","biblical","bible","jesus","moses","david","abraham","saint"],
  "Présence de Dieu": ["présence","présence divine","présence du seigneur","présence de dieu","immanence","immanent","immanente","omniscience","omniscient","omnisciente","omnipotence","omnipotent","omnipotente","omniprésence","omniprésent","omniprésente","proximité divine","proximité de dieu","communion","communier","fusion","fusion spirituelle","union mystique","union à dieu","dieu est avec moi","je sens la présence de dieu","dieu m'accompagne","sentir dieu","divine presence","communion","intimacy with god"],
  "Promesses": ["promesse","promesses","promettre","promis","promise","engagement","s'engager","engagé","engagée","contrat","contrat divin","alliance","allié","alliée","pacte","pacte divin","serment","serments","jurer","juré","jurée","vœu","vœux","voeu","assurance","assurer","assuré","assurée","garantie","garanti","engagement divin","engagement de dieu","dieu a promis","les promesses de dieu","tenir la promesse","promise","covenant","oath","vow","assurance"],
  "Relation": ["relation","relations","rapport","rapports","lien","liens","connexion","connexions","association","associé","associée","amitié","amis","amie","fraternité","fraternel","fraternelle","frère","sororité","sororale","sœur","communauté","communautaire","interdépendance","interdépendant","interdépendante","lien affectif","lien émotionnel","lien familial","lien social","notre relation","liens sociaux","relationship","bond","friendship","connection"],
  "Retour à Dieu": ["retour","revenir","revenu","revenue","conversion","converti","convertie","convertir","repentance","repentant","repentante","se repentir","réconciliation","se réconcilier","réconcilié","réconciliée","rédemption","rédempteur","rédemptrice","racheté","rachetée","restauration","restaurer","restauré","restaurée","renouvellement","renouveler","renouvelé","renouvelée","renaissance","renaître","renée","renés","résurrection","ressusciter","ressuscité","ressuscitée","illumination","illuminer","illuminé","illuminée","transformation","transformer","transformé","transformée","guérison spirituelle","retour à la foi","revenir à dieu","retour au seigneur","conversion","redemption","return"],
  "Restauration": ["restauration","restaurer","restauré","restaurée","réparation","réparer","réparé","réparée","reconstruction","reconstruire","reconstruit","reconstruite","réhabilitation","réhabiliter","réhabilité","réhabilitée","rétablissement","rétablir","rétabli","rétablie","restitution","restituer","restitué","restituée","redressement","redresser","redressé","redressée","guérison","guérir","guéri","guérie","réconciliation","réconcilier","réconcilié","réconciliée","renouvellement","renouveler","renouvelé","renouvelée","rapiéçage","rapiécer","restauration de la confiance","restoration","repair","rehabilitation"],
  "Saint-Esprit": ["saint-esprit","esprit saint","esprit","paraclet","consolateur","consolatrice","advocate","onction","oint","ointe","onction du saint-esprit","baptême du saint-esprit","baptême de l'esprit","remplissage du saint-esprit","remplissage de l'esprit","fruits de l'esprit","dons du saint-esprit","dons de l'esprit","charisme","charismatique","prophétie","prophète","prophétesse","prophétique","glossolalie","parler en langues","guérison spirituelle","discernement","sagesse divine","rempli du saint-esprit","l'esprit de dieu","action du saint-esprit","présence de l'esprit saint","holy spirit","spirit","paraclete","spiritual gifts"],
  "Travail et richesse": ["travail","travailler","travaillé","travaillée","emploi","emplois","employé","employée","profession","professionnel","professionnelle","métier","métiers","carrière","carrières","salaire","salaires","revenu","revenus","richesse","riche","riches","prospérité","prospère","abondance","abondant","abondante","bénédiction économique","richesse matérielle","richesse financière","épreuve financière","difficulté financière","insécurité économique","instabilité économique","entreprise","entrepreneur","entrepreneuriat","commerce","commerciaux","commerciale","industrie","industriel","industrielle","bénédiction dans mon travail","dieu bénit mon emploi","providence économique","work","employment","wealth","prosperity","income","career"],
  "Décision": ["décision","décisions","décider","décidé","décidée","choix","choisir","choisi","choisie","option","options","alternative","alternatives","sélection","sélectionner","sélectionné","sélectionnée","résolution","résolu","résolue","détermination","déterminé","déterminée","orientation","orienter","orienté","orientée","direction","directions","chemin","chemins","voie","voies","direction divine","guidance divine","guidance","guidance de dieu","discernement","discerner","discerné","discernée","je dois décider","quelle décision prendre","dieu guide ma décision","decision","choice","direction","guidance","discernment"],
  "Louange": ["louange","louanges","louer","loué","louée","louanges à dieu","louange du seigneur","adoration","adorer","adoré","adorée","glorification","glorifier","glorifié","glorifiée","exaltation","exalter","exalté","exaltée","reconnaissance","reconnaître","reconnu","reconnue","gratitude","reconnaissant","reconnaissante","hymne","hymnes","hymne religieux","chant","chants","chant religieux","psalmodie","psalmodier","magnificence","magnifique","gloire","glorieux","glorieuse","louer le seigneur","gloire à dieu","dieu soit béni","cantique de louange","praise","worship","glory","hymn"],
  "Pensée": ["pensée","pensées","réflexion","réfléchir","réfléchi","réfléchie","méditation","méditer","médité","méditée","contemplation","contempler","contemplé","contemplée","cogitation","cogiter","cogité","cogitée","rumination","ruminer","ruminé","ruminée","idée","idées","opinion","opinions","concept","concepts","croyance","croyances","croire","conviction","convictions","convaincu","convaincue","certitude","certain","certaine","incertitude","incertain","incertaine","doute","douter","douteux","douteuse","dieu m'a fait réfléchir","j'ai médité","j'ai pensé","thought","reflection","meditation","contemplation","conviction"],
  "Gratitude": ["gratitude","reconnaissant","reconnaissante","reconnaissance","reconnaître","reconnu","reconnue","merci","mercis","remerciement","remercier","remercié","remerciée","action de grâce","actions de grâce","gratification","gratifier","gratifié","gratifiée","appréciation","apprécier","apprécié","appréciée","admiration","admirer","admiré","admirée","respect","respecter","respecté","respectée","estime","estimer","estimé","estimée","merci à dieu","je suis reconnaissant","dieu je te remercie","gloire et honneur à dieu","gratitude","thankfulness","appreciation","thanksgiving"],
  "Fondations": ["fondations","fondamental","fondamentale","base","bases","basique","fondement","fondements","principes","principaux","principale","socle","socles","infrastructure","infrastructures","pilier","piliers","ancrage","ancrer","ancré","ancrée","solidité","solide","stabilité","stable","structure","structures","structurel","structurelle","édifice","châssis","architecture","architectural","architecturale","les fondations de ma foi","fondations solides","sur le roc","foundations","fundamentals","pillars","bedrock"],
  "Renouvellement": ["renouvellement","renouveler","renouvelé","renouvelée","renaissance","renaître","renée","renés","restauration","restaurer","restauré","restaurée","régénération","régénérer","régénéré","régénérée","rénovation","rénover","rénové","rénovée","transformation","transformer","transformé","transformée","mutation","muter","muté","mutée","changement","changer","changé","changée","évolution","évoluer","évolué","progrès","progresser","progressé","amélioration","améliorer","amélioré","améliorée","rajeunissement","rajeunir","rajeuni","rajeunie","revitalisation","revitaliser","revitalisé","revitalisée","nouveau départ","recommencer","je suis renouvelé","renewal","regeneration","revival","new beginning"]
};

// ── Normalisation : minuscules + suppression accents ──────────────
function normalizeText(text) {
  if (!text) return "";
  return String(text)
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, ""); // retire les diacritiques
}

// ── Échappement regex (pour les mots-clés contenant des caractères spéciaux) ──
function escapeRegex(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * classifyTestimony(transcription, keywordsConfig?)
 * ─────────────────────────────────────────────────
 * @param {string} transcription — le texte à analyser
 * @param {object} keywordsConfig — optionnel : objet { catégorie: [mots] }.
 *        Si absent → on tente getConfig().categoriesKeywords, sinon DEFAULT_KEYWORDS.
 * @returns {string|null} — la catégorie proposée (ou null si aucun match)
 */
function classifyTestimony(transcription, keywordsConfig) {
  if (!transcription || !String(transcription).trim()) return null;

  // Source des mots-clés : argument > config.json > défaut
  let keywords = keywordsConfig;
  if (!keywords) {
    try {
      const { getConfig } = require('./config');
      const cfg = getConfig();
      keywords = (cfg.categoriesKeywords && Object.keys(cfg.categoriesKeywords).length)
        ? cfg.categoriesKeywords
        : DEFAULT_KEYWORDS;
    } catch {
      keywords = DEFAULT_KEYWORDS;
    }
  }

  const normalized = normalizeText(transcription);
  const scores = {};

  for (const [category, list] of Object.entries(keywords)) {
    if (!Array.isArray(list)) continue;
    let score = 0;
    for (const kw of list) {
      const nkw = normalizeText(kw);
      if (!nkw) continue;
      // \b limite de mot ; échappement pour les apostrophes/tirets
      const regex = new RegExp(`\\b${escapeRegex(nkw)}\\b`, "g");
      const matches = normalized.match(regex);
      if (matches) score += matches.length;
    }
    if (score > 0) scores[category] = score;
  }

  if (Object.keys(scores).length === 0) return null;

  const maxScore = Math.max(...Object.values(scores));
  // En cas d'égalité : première catégorie dans l'ordre de définition
  const top = Object.keys(scores).find(c => scores[c] === maxScore);
  return top || null;
}

module.exports = { classifyTestimony, normalizeText, DEFAULT_KEYWORDS };
